package com.safar.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

@Data
@DynamoDBTable(tableName = "admin")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Admin {

    @DynamoDBHashKey(attributeName = "adminID")
    @DynamoDBAutoGeneratedKey
    private Integer adminID;

    @NotNull(message = "Name can not be null!")
    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @Email
    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @NotNull(message="Password can not be null!")
    @DynamoDBAttribute(attributeName = "password")
    @Pattern(regexp = "[A-Za-z0-9!@#$%^&*_]{8,15}", message = "Password must be 8-15 characters including alphanumerics and special characters")
    private String password;

}
