package com.safar.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "user")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User1 {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName ="firstName")
    private String firstName;

    @DynamoDBAttribute(attributeName="lastName")
    private String lastName;

    @DynamoDBAttribute(attributeName = "number")
    private String number;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

}


