package com.safar.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@Data
@DynamoDBTable(tableName = "user")
public class User {

    @DynamoDBHashKey(attributeName = "userID")
    @DynamoDBAutoGeneratedKey
    private Integer userID;

    @DynamoDBAttribute(attributeName = "firstName")
    @NotNull(message = "Name cannot be null!")
    @NotBlank(message = "Name cannot be blank!")
    private String firstName;

    @DynamoDBAttribute(attributeName = "lastName")
    private String lastName;

    @DynamoDBAttribute(attributeName = "mobile")
    @NotNull(message = "Mobile number cannot be null!")
    @NotBlank(message = "Mobile number cannot be blank!")
    @Pattern(regexp = "[6789]{1}[0-9]{9}", message = "Enter a valid 10-digit mobile number")
    @Size(min = 10, max = 10)
    private String mobile;

    @DynamoDBAttribute(attributeName = "email")
    @Email
    private String email;

    @DynamoDBAttribute(attributeName = "password")
    @NotNull(message = "Password cannot be null!")
    @NotBlank(message = "Password cannot be blank!")
    @Pattern(regexp = "[A-Za-z0-9!@#$%^&*_]{8,15}", message = "Password must be 8-15 characters including alphanumerics and special characters")
    private String password;
}
